### ISSUE TITLE
test_login cannot find target service for Bildungsmonitoring and Landesdatenbank NRW

### ISSUE THREAD

**Issue by RichardMeyer-Eppler** [sumtxt/wiesbaden#11]
Testing my login information for the Bildungsmonitoring and Landesdatenbank NRW fails with the error messages below, even though it has worked fine before. When logging in through the website, I noticed that my password had expired and I was prompted to set a new one. Even with updated passwords, I still get the error messages below. Any ideas as to why?

``` r
wiesbaden::test_login(
  genesis = c(db = "nrw")
)
#> [1] "ns1:Server.NoServiceThe AXIS engine could not find a target service to invoke!  targetService is TestServicesb2-itd-278.admin.sb2"

wiesbaden::test_login(
  genesis = c(db = "bm")
)
#> [1] "ns1:Server.NoServiceThe AXIS engine could not find a target service to invoke!  targetService is TestServicesb2-itd-333.admin.sb2"
```

<sup>Created on 2020-08-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.0.2 (2020-06-22)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  German_Germany.1252         
#>  ctype    German_Germany.1252         
#>  tz       Europe/Berlin               
#>  date     2020-08-15                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version date       lib source                           
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.2)                   
#>  backports     1.1.8   2020-06-17 [1] CRAN (R 4.0.2)                   
#>  callr         3.4.3   2020-03-28 [1] CRAN (R 4.0.2)                   
#>  cli           2.0.2   2020-02-28 [1] CRAN (R 4.0.2)                   
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.2)                   
#>  curl          4.3     2019-12-02 [1] CRAN (R 4.0.2)                   
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.2)                   
#>  devtools      2.3.0   2020-04-10 [1] CRAN (R 4.0.2)                   
#>  digest        0.6.25  2020-02-23 [1] CRAN (R 4.0.2)                   
#>  ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.2)                   
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.2)                   
#>  fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.2)                   
#>  fs            1.4.2   2020-06-30 [1] CRAN (R 4.0.2)                   
#>  glue          1.4.1   2020-05-13 [1] CRAN (R 4.0.2)                   
#>  highr         0.8     2019-03-20 [1] CRAN (R 4.0.2)                   
#>  hms           0.5.3   2020-01-08 [1] CRAN (R 4.0.2)                   
#>  htmltools     0.5.0   2020-06-16 [1] CRAN (R 4.0.2)                   
#>  httr          1.4.2   2020-07-20 [1] CRAN (R 4.0.2)                   
#>  jsonlite      1.7.0   2020-06-25 [1] CRAN (R 4.0.2)                   
#>  keyring       1.1.0   2018-07-16 [1] CRAN (R 4.0.2)                   
#>  knitr         1.29    2020-06-23 [1] CRAN (R 4.0.2)                   
#>  lifecycle     0.2.0   2020-03-06 [1] CRAN (R 4.0.2)                   
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 4.0.2)                   
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 4.0.2)                   
#>  pillar        1.4.6   2020-07-10 [1] CRAN (R 4.0.2)                   
#>  pkgbuild      1.1.0   2020-07-13 [1] CRAN (R 4.0.2)                   
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.2)                   
#>  pkgload       1.1.0   2020-05-29 [1] CRAN (R 4.0.2)                   
#>  prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.2)                   
#>  processx      3.4.3   2020-07-05 [1] CRAN (R 4.0.2)                   
#>  ps            1.3.3   2020-05-08 [1] CRAN (R 4.0.2)                   
#>  R6            2.4.1   2019-11-12 [1] CRAN (R 4.0.2)                   
#>  Rcpp          1.0.5   2020-07-06 [1] CRAN (R 4.0.2)                   
#>  readr         1.3.1   2018-12-21 [1] CRAN (R 4.0.2)                   
#>  remotes       2.1.1   2020-02-15 [1] CRAN (R 4.0.2)                   
#>  rlang         0.4.7   2020-07-09 [1] CRAN (R 4.0.2)                   
#>  rmarkdown     2.3     2020-06-18 [1] CRAN (R 4.0.2)                   
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 4.0.2)                   
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.2)                   
#>  stringi       1.4.6   2020-02-17 [1] CRAN (R 4.0.0)                   
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.2)                   
#>  testthat      2.3.2   2020-03-02 [1] CRAN (R 4.0.2)                   
#>  tibble        3.0.3   2020-07-10 [1] CRAN (R 4.0.2)                   
#>  usethis       1.6.1   2020-04-29 [1] CRAN (R 4.0.2)                   
#>  vctrs         0.3.2   2020-07-15 [1] CRAN (R 4.0.2)                   
#>  wiesbaden     1.2.3   2020-08-15 [1] Github (sumtxt/wiesbaden@d36213b)
#>  withr         2.2.0   2020-04-20 [1] CRAN (R 4.0.2)                   
#>  xfun          0.15    2020-06-21 [1] CRAN (R 4.0.2)                   
#>  xml2          1.3.2   2020-04-23 [1] CRAN (R 4.0.2)                   
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.0)                   
#> 
#> [1] D:/Data/Documents/R/win-library/4.0
#> [2] C:/Program Files/R/R-4.0.2/library
```

</details>

**Comment by sumtxt** [comment]
Thank you. I can reproduce the error which is server-side. I email the admin about this.

**Comment by sumtxt** [comment]
Fixed now. Please reinstall via `remotes::install_github("sumtxt/wiesbaden")` Commit:  a22216de89adf5523a74824ca663cfdb9db28cb7

**Comment by RichardMeyer-Eppler** [comment]
Thanks for the fix, worked for me!

Did not work right away, though: when I first used `remotes::install_github("sumtxt/wiesbaden")`, the problem persisted. I had to use `remotes::install_github("sumtxt/wiesbaden", force = TRUE)`, after which everything worked fine.

I guess what happened is that the install check did not realize that the package had updated and simply kept my installed version. Presumably you updated the package without a version / hash change, or something similar?

**Comment by sumtxt** [comment]
Not sure why force=TRUE is necessary but happy to hear that it works now.

**Comment by foobar32** [comment]
I had the very same problem with the regio database
reinstalling as described above (using force = T) worked.
This might be a bigger issue and might be worth being noted in the vignette and manual

(speaking of vignette/manual - you probably want to change your wording from theme to topic in these documents)
